import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

// Super Admin — system oversight, view-only for operational actions like PO creation.
// Super Admin oversees but does not transact. Warehouse Managers create POs.
const SUPER_ADMIN_PERMISSIONS = ALL_PERMISSIONS.filter(
  (p) => ![
    PERMISSIONS.PO_CREATE,
    PERMISSIONS.PO_EDIT,
    PERMISSIONS.PO_RECEIVE,
  ].includes(p)
);

// Warehouse Manager — read-only on Receiving/Picking/Shipping ops, can approve orders,
// has admin access to Facilities, Locations, Users, Clients, Reports
const WAREHOUSE_MANAGER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DASHBOARD_ANALYTICS,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.PRODUCTS_CREATE,
  PERMISSIONS.PRODUCTS_EDIT,
  PERMISSIONS.PRODUCTS_IMPORT,
  PERMISSIONS.PRODUCTS_EXPORT,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.INVENTORY_ADJUST,
  PERMISSIONS.INVENTORY_MOVEMENTS,
  PERMISSIONS.INVENTORY_EXPORT,
  PERMISSIONS.BATCH_VIEW,
  PERMISSIONS.BATCH_CREATE,
  PERMISSIONS.BATCH_EDIT,
  PERMISSIONS.EXPIRY_VIEW,
  PERMISSIONS.EXPIRY_MANAGE,
  PERMISSIONS.PO_VIEW,
  // No PO_CREATE, PO_EDIT, PO_RECEIVE, RECEIVING_EXECUTE — read-only on Receiving
  PERMISSIONS.PO_APPROVE,
  PERMISSIONS.PO_DELETE,
  PERMISSIONS.TO_VIEW,
  PERMISSIONS.TO_CREATE,
  PERMISSIONS.TO_EDIT,
  PERMISSIONS.TO_EXECUTE,
  PERMISSIONS.SO_VIEW,
  PERMISSIONS.SO_CREATE,
  PERMISSIONS.SO_EDIT,
  PERMISSIONS.SO_APPROVE,  // Can approve/reject sales orders
  PERMISSIONS.SO_DELETE,
  PERMISSIONS.SO_PICK,     // Added to view picking menu
  // No PICKING_EXECUTE — read-only on Picking
  PERMISSIONS.SHIPPING_VIEW,
  PERMISSIONS.SHIPPING_TRACK,
  // No SHIPPING_CREATE, SHIPPING_EXECUTE, SHIPPING_DELETE — read-only on Shipping
  PERMISSIONS.WAREHOUSE_VIEW,
  PERMISSIONS.WAREHOUSE_MANAGE,
  PERMISSIONS.WAREHOUSE_ZONES,
  PERMISSIONS.WAREHOUSE_LOCATIONS,
  PERMISSIONS.FACILITIES_VIEW,
  PERMISSIONS.BARCODE_VIEW,
  PERMISSIONS.BARCODE_GENERATE,
  PERMISSIONS.BARCODE_PRINT,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_EDIT,
  PERMISSIONS.USERS_DELETE,
  PERMISSIONS.CLIENTS_VIEW,
  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

// Inventory Clerk — full operational access to Receiving, Picking, Shipping, Barcode, Transfers
// No access to Facilities, Locations, Users, Clients, Reports, or order approval
const INVENTORY_CLERK_PERMISSIONS = ALL_PERMISSIONS.filter(
  (p) => ![
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.USERS_DELETE,
  ].includes(p)
);

// Client — access to portal, inventory, shipping tracking & sales orders
const CLIENT_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.BATCH_VIEW,
  PERMISSIONS.EXPIRY_VIEW,
  PERMISSIONS.CLIENT_PORTAL_VIEW,
  PERMISSIONS.CLIENT_ORDERS_VIEW,
  PERMISSIONS.CLIENT_TRACKING_VIEW,
  PERMISSIONS.CLIENT_REPORTS_VIEW,
  PERMISSIONS.SO_VIEW,
  PERMISSIONS.WAREHOUSE_VIEW,
  PERMISSIONS.SHIPPING_VIEW,
  PERMISSIONS.SHIPPING_TRACK,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
  [ROLES.WAREHOUSE_MANAGER]: WAREHOUSE_MANAGER_PERMISSIONS,
  [ROLES.INVENTORY_CLERK]: INVENTORY_CLERK_PERMISSIONS,
  [ROLES.CLIENT]: CLIENT_PERMISSIONS,
};

// Apply administrator-saved RBAC overrides when the browser session starts.
// Temporarily disabled to allow new permissions to take effect for WAREHOUSE_MANAGER
/*
if (typeof localStorage !== 'undefined') {
  try {
    const savedPermissions = JSON.parse(localStorage.getItem('wms_role_permissions') || 'null');
    if (savedPermissions) {
      Object.keys(savedPermissions).forEach((role) => {
        if (ROLE_PERMISSIONS[role] && Array.isArray(savedPermissions[role])) {
          ROLE_PERMISSIONS[role] = savedPermissions[role];
        }
      });
    }
  } catch {
    localStorage.removeItem('wms_role_permissions');
  }
}
*/
