import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

// Super Admin gets all permissions
const SUPER_ADMIN_PERMISSIONS = ALL_PERMISSIONS;

// Warehouse Manager — full operational access, no system settings or user management
const WAREHOUSE_MANAGER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DASHBOARD_ANALYTICS,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.PRODUCTS_CREATE,
  PERMISSIONS.PRODUCTS_EDIT,
  PERMISSIONS.PRODUCTS_IMPORT,
  PERMISSIONS.PRODUCTS_EXPORT,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.INVENTORY_ADJUST,
  PERMISSIONS.INVENTORY_MOVEMENTS,
  PERMISSIONS.INVENTORY_EXPORT,
  PERMISSIONS.BATCH_VIEW,
  PERMISSIONS.BATCH_CREATE,
  PERMISSIONS.BATCH_EDIT,
  PERMISSIONS.EXPIRY_VIEW,
  PERMISSIONS.EXPIRY_MANAGE,
  PERMISSIONS.PO_VIEW,
  PERMISSIONS.PO_CREATE,
  PERMISSIONS.PO_EDIT,
  PERMISSIONS.PO_APPROVE,
  PERMISSIONS.PO_RECEIVE,
  PERMISSIONS.TO_VIEW,
  PERMISSIONS.TO_CREATE,
  PERMISSIONS.TO_EDIT,
  PERMISSIONS.TO_EXECUTE,
  PERMISSIONS.SO_VIEW,
  PERMISSIONS.SO_CREATE,
  PERMISSIONS.SO_EDIT,
  PERMISSIONS.SO_PICK,
  PERMISSIONS.SO_SHIP,
  PERMISSIONS.WAREHOUSE_VIEW,
  PERMISSIONS.WAREHOUSE_MANAGE,
  PERMISSIONS.WAREHOUSE_ZONES,
  PERMISSIONS.WAREHOUSE_LOCATIONS,
  PERMISSIONS.BARCODE_VIEW,
  PERMISSIONS.BARCODE_GENERATE,
  PERMISSIONS.BARCODE_PRINT,
  PERMISSIONS.SHIPPING_VIEW,
  PERMISSIONS.SHIPPING_CREATE,
  PERMISSIONS.SHIPPING_TRACK,
  PERMISSIONS.SHIPPING_MANAGE,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

// Inventory Clerk — read and limited write on core inventory
const INVENTORY_CLERK_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.PRODUCTS_CREATE,
  PERMISSIONS.PRODUCTS_EDIT,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.INVENTORY_ADJUST,
  PERMISSIONS.INVENTORY_MOVEMENTS,
  PERMISSIONS.BATCH_VIEW,
  PERMISSIONS.BATCH_CREATE,
  PERMISSIONS.EXPIRY_VIEW,
  PERMISSIONS.PO_VIEW,
  PERMISSIONS.PO_RECEIVE,
  PERMISSIONS.TO_VIEW,
  PERMISSIONS.TO_EXECUTE,
  PERMISSIONS.SO_VIEW,
  PERMISSIONS.SO_PICK,
  PERMISSIONS.WAREHOUSE_VIEW,
  PERMISSIONS.WAREHOUSE_LOCATIONS,
  PERMISSIONS.BARCODE_VIEW,
  PERMISSIONS.BARCODE_GENERATE,
  PERMISSIONS.BARCODE_PRINT,
  PERMISSIONS.SHIPPING_VIEW,
  PERMISSIONS.SHIPPING_TRACK,
  PERMISSIONS.REPORTS_VIEW,
];

// Client — limited read-only access to their portal
const CLIENT_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.PRODUCTS_VIEW,
  PERMISSIONS.BATCH_VIEW,
  PERMISSIONS.EXPIRY_VIEW,
  PERMISSIONS.CLIENT_PORTAL_VIEW,
  PERMISSIONS.CLIENT_ORDERS_VIEW,
  PERMISSIONS.CLIENT_TRACKING_VIEW,
  PERMISSIONS.CLIENT_REPORTS_VIEW,
  PERMISSIONS.SO_VIEW,
  PERMISSIONS.SHIPPING_TRACK,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
];

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
  [ROLES.WAREHOUSE_MANAGER]: WAREHOUSE_MANAGER_PERMISSIONS,
  [ROLES.INVENTORY_CLERK]: INVENTORY_CLERK_PERMISSIONS,
  [ROLES.CLIENT]: CLIENT_PERMISSIONS,
};

// Apply administrator-saved RBAC overrides when the browser session starts.
if (typeof localStorage !== 'undefined') {
  try {
    const savedPermissions = JSON.parse(localStorage.getItem('wms_role_permissions') || 'null');
    if (savedPermissions) {
      Object.keys(savedPermissions).forEach((role) => {
        if (ROLE_PERMISSIONS[role] && Array.isArray(savedPermissions[role])) {
          ROLE_PERMISSIONS[role] = savedPermissions[role];
        }
      });
    }
  } catch {
    localStorage.removeItem('wms_role_permissions');
  }
}
